<?php
sajax_export(
    "return_oneParametre",
    "return_allParametre",
    "action_updateParametre",
    "action_insertParametre",
    "return_infoAppli",
    "return_depotsBAV",
    "return_tauxBAV"
);
