<?php
sajax_export(
    "return_oneClient",
    "action_updateClient",
    "action_makeClient",
    "return_oneClientByMel",
    "return_oneClientByIdModif",
    "return_listClientByMel",
    "return_listClientByName",
    "return_oneClientByName",
    "return_clients","return_clientsRecap",
    "action_deleteClient",
    "return_bavsClient"
);
