<?php
sajax_export(
    "return_oneClient",
    "action_updateClient",
    "action_insertClient",
    "return_oneClientByMel",
    "return_oneClientByIdModif",
    "return_listClientByMel",
    "return_listClientByName",
    "return_oneClientByName",
    "return_clients"
);
