
--
-- Contenu de la table `bav_actu`
--

INSERT INTO `bav_actu` (`act_id`, `act_titre`, `act_text`, `act_numero_bav`, `act_type`, `act_active`, `act_date`, `act_mail`) VALUES
(1, 'Est-ce qu&#39;il faut remplir un formulaire pour s&rsquo;inscrire &agrave; l&#39;avance ou peux t&#39;on simplement se pr&eacute;senter avec notre v&eacute;lo sans inscription pr&eacute;alable ?', 'Les deux solutions sont possibles. Dans l&#39;onglet &quot;T&eacute;l&eacute;chargements&quot; vous trouverez un exemplaire du formulaire que vous pouvez remplir &agrave; l&#39;avance pour vous faire gagner du temps sur place.<br />\nSinon, tous les formulaires sont mis &agrave; votre disposition sur place.<br />\n<span style=\"background-color:#2ecc71\">**N&#39;oubliez pas votre pi&egrave;ce d&#39;identit&eacute;.**</span>', 2019, 'FAQ', 1, '2010-07-26 07:47:47', 'notsupplied@notsupplied.com'),
(18, 'Presse Oc&eacute;an - Octobre 2017', '<img alt=\"\" src=\"http://avs44.com/bourseauxvelos/ckeditorUploads/6583b5a.png\" />', 2017, 'PRESSE', 1, '2019-02-05 10:14:28', NULL),
(19, 'Estuaire Hebdo - Octobre 2017', '<img alt=\"\" src=\"http://avs44.com/bourseauxvelos/ckeditorUploads/473e0ec.png\" />', 2017, 'PRESSE', 1, '2019-02-05 10:15:18', NULL),
(20, 'Ouest France - 07/11/2016', '<div><a href=\"http://avs44.com/bourseauxvelos/ckeditorUploads/7f23bcc.jpg\" target=\"_blank\"><img alt=\"\" src=\"http://avs44.com/bourseauxvelos/ckeditorUploads/7f23bcc.jpg\" /></a></div>\n', 2016, 'PRESSE', 1, '2019-02-05 10:15:46', NULL),
(21, 'Presse Oc&eacute;an - 07/11/2016', '<img alt=\"\" src=\"http://avs44.com/bourseauxvelos/ckeditorUploads/5c52007.jpg\" />', 2016, 'PRESSE', 1, '2019-02-05 10:20:25', NULL),
(22, 'Ouest France - 06/11/2016', '<img alt=\"\" src=\"http://avs44.com/bourseauxvelos/ckeditorUploads/8d8d613.jpg\" />', 2016, 'PRESSE', 1, '2016-11-26 10:21:49', NULL),
(23, 'Ouest France - 04/11/2016', '<img alt=\"\" src=\"http://avs44.com/bourseauxvelos/ckeditorUploads/9a82cca.jpg\" />', 2016, 'PRESSE', 1, '2019-02-05 10:23:11', NULL),
(24, 'Echo de la Prequ&#39;&icirc;le - 04/11/2016', '<img alt=\"\" src=\"http://avs44.com/bourseauxvelos/ckeditorUploads/114eb167.jpg\" />', 2016, 'PRESSE', 1, '2019-02-05 10:25:20', NULL),
(25, 'Presse Oc&eacute;an - 31/10/2016', '<img alt=\"\" src=\"http://avs44.com/bourseauxvelos/ckeditorUploads/10227624.jpg\" />', 2016, 'PRESSE', 1, '2019-02-05 10:26:55', NULL),
(26, 'Presse Oc&eacute;an - 09/11/2015', '<img alt=\"\" src=\"http://avs44.com/bourseauxvelos/ckeditorUploads/1135e0c8.png\" />', 2015, 'PRESSE', 1, '2019-02-05 10:30:13', NULL),
(27, 'Presse Oc&eacute;an - 09/11/2015', '<img alt=\"\" src=\"http://avs44.com/bourseauxvelos/ckeditorUploads/124f9fb1.jpg\" />', 2015, 'PRESSE', 1, '2019-02-05 10:42:14', NULL),
(28, 'Ouest France - 08/11/2015', '<img alt=\"\" src=\"http://avs44.com/bourseauxvelos/ckeditorUploads/14f1f302.jpg\" /><br />\n<img alt=\"\" src=\"http://avs44.com/bourseauxvelos/ckeditorUploads/137d849b.jpg\" />', 2015, 'PRESSE', 1, '2019-02-05 10:44:00', NULL),
(29, 'Presse Oc&eacute;an - 03/11/2015', '<img alt=\"\" src=\"http://avs44.com/bourseauxvelos/ckeditorUploads/15044672.jpg\" />', 2015, 'PRESSE', 1, '2019-02-05 10:45:38', NULL),
(30, 'Ouest France - 04/11/2015', '<img alt=\"\" src=\"http://avs44.com/bourseauxvelos/ckeditorUploads/164d11b9.jpg\" />', 2015, 'PRESSE', 1, '2019-02-05 10:46:46', NULL),
(31, 'Ouest France - 04/11/2015', '<img alt=\"\" src=\"http://avs44.com/bourseauxvelos/ckeditorUploads/17c11448.jpg\" />', 2015, 'PRESSE', 1, '2019-02-05 10:48:58', NULL),
(32, 'Ouest France - 18/11/2018', '<img alt=\"\" src=\"http://avs44.com/bourseauxvelos/ckeditorUploads/182e7897.jpg\" />', 2018, 'PRESSE', 1, '2019-02-05 10:53:06', NULL),
(33, 'PRESSE OC&Eacute;AN - D&Eacute;CEMBRE 2014', '<img alt=\"\" src=\"http://avs44.com/bourseauxvelos/ckeditorUploads/198b7d55.jpg\" />', 2014, 'PRESSE', 1, '2019-02-06 10:43:29', NULL),
(37, 'Tombola', '<img alt=\"\" height=\"115\" src=\"http://avs44.com/bourseauxvelos/ckeditorUploads/terre_de_cycle_logo.png\" width=\"396\" /><br />\nPendant l&#39;&eacute;dition 2018, chaque acheteur, vendeur ou visiteur pourra s&#39;il le souhaite participer &agrave; la tombola gratuite de <strong>la Bourse aux V&eacute;los </strong>pour gagner un tr&egrave;s beau VTT NEUF de chez &quot;<strong>Terre de Cycle</strong>&quot; &agrave; La Baule.<br />\nTirage au sort le dimanche soir vers 17h30.<br />\n<br />\n==&gt;&nbsp;<a href=\"http://avs44.com/bourseauxvelos/downloads/reglement_tombola.pdf\" target=\"_blank\">reglement de la tombola</a>', 2018, 'ANIM', 1, '2019-02-07 12:02:48', NULL),
(38, 'Bruno Robineau, cr&eacute;ateur de v&eacute;los miniatures faits main', '&nbsp;\n<table cellpadding=\"1\" cellspacing=\"1\" style=\"width:100%\">\n	<tbody>\n		<tr>\n			<td><img alt=\"\" height=\"128\" src=\"http://avs44.com/bourseauxvelos/ckeditorUploads/velodubonheur.png\" width=\"200\" /></td>\n			<td><img alt=\"\" height=\"127\" src=\"http://localhost/bourseauxvelos/ckeditorUploads/velos_decoratifs_2018.jpg\" width=\"189\" /></td>\n		</tr>\n	</tbody>\n</table>\n<br />\nBruno ROBINEAU participera &agrave; notre bourse aux v&eacute;los, ne manquez pas de visiter son stand.<br />\nEn plus d&rsquo;une large gamme de plus de 20 v&eacute;los miniatures faits main avec un seul fil , il y pr&eacute;sentera ses r&eacute;cits de voyage : Huit ans autour du monde, Compostelle en famille, Roumanie vagabonde.<br />\n&nbsp;<a href=\"http://avs44.com/bourseauxvelos/Images/animations/velos_miniatures_2018.pdf\">Plus d&#39;informations</a>', 2018, 'ANIM', 1, '2019-02-07 11:13:23', NULL),
(41, 'Est-ce qu&#39;il y a des cars qui desservent La Soucoupe de Saint Nazaire en partant de St Nazaire/La Gare SNCF ?', 'Effectivement, il y a de nombreux bus qui d&eacute;servent la gare et La Soucoupe ou est organis&eacute;e la bourse.<br />\nPrenez qu&rsquo;un aller simple car il se peut que vous repartiez avec le v&eacute;lo de vos r&ecirc;ves&hellip;!', 2019, 'FAQ', 1, '2010-07-26 07:42:59', 'notsupplied@notsupplied.com'),
(42, 'Est-ce que les v&eacute;los de course seront accept&eacute;s ?', 'Tous les v&eacute;los sont accept&eacute;s dont les v&eacute;los de course &agrave; condition qu&#39;ils soient en &eacute;tat de rouler.', 2019, 'FAQ', 1, '2010-07-26 07:50:21', 'notsupplied@notsupplied.com'),
(43, 'Je recherche un v&eacute;lo pour mon fils de 7 ans 1/2 qui mesure 1m29, entrejambe 58 cm, dois je prendre un 20 ou un 24 pouces sachant qu&rsquo;il grandisse vite &agrave; cet age l&agrave;.<br />\nC&#39;est un cadeau donc je ne peux l&rsquo;enmener avec moi.<br />\nJe voudrais trouver un v&eacute;lo en tr&egrave;s bonne &eacute;tat,peut on trouver &ccedil;a dans votre manifestation pour un prix r&eacute;sonnable ?', 'Nous ne pouvons &agrave; cette heure conna&icirc;tre le choix que nous aurons cette ann&eacute;e mais les autres ann&eacute;es, il y avait ce que vous cherchez.<br />\nLe mieux, c&rsquo;est de nous rendre visite d&egrave;s le samedi matin fin de matin&eacute;e au moment o&ugrave; il y a plus de choix. Nos vendeurs b&eacute;n&eacute;voles vous conseilleront.', 2019, 'FAQ', 1, '2010-07-26 07:54:07', 'notsupplied@notsupplied.com'),
(44, 'Je suis absent le samedi; est il possible de d&eacute;poser le v&eacute;lo que je veux vendre la veille au soir au gymnase? ou bien alors le dimanche matin?<br />\nEn vous remerciant pour votre r&eacute;ponse.', '<span style=\"background-color:#f39c12\">NOUVEAU depuis 2013&nbsp;: </span>Pour &eacute;viter l&rsquo;affluence du samedi matin nous commen&ccedil;ons les d&eacute;p&ocirc;ts (Uniquement les d&eacute;p&ocirc;ts) d&egrave;s le vendredi de 18h &agrave; 21h00 m&ecirc;me lieu La Soucoupe gard&eacute;e la nuit.', 2019, 'FAQ', 1, '2010-10-15 08:16:22', 'r.dupain@voila.fr'),
(45, 'Faut&#39;il r&eacute;cup&eacute;rer imp&eacute;rativement le v&eacute;lo le dimanche soir ou possibilit&eacute;&nbsp;le lundi matin ?', 'Malheureusement, nous devons lib&eacute;rer la salle le dimanche soir donc nous n&#39;avons pas la possibilit&eacute; de stocker les v&eacute;los non-vendus. Il est donc imp&eacute;ratif de r&eacute;cup&eacute;rer le v&eacute;lo le dimanche soir au plus tard.', 2019, 'FAQ', 1, '2010-10-25 08:39:46', 'cricri.doudou@free.fr'),
(46, 'Si je depose le velo samedi matin dois je le recuperer le soir pour le redeposer le dimanche', 'Non, il n&#39;est pas n&eacute;cessaire de r&eacute;cup&eacute;rer votre v&eacute;lo et red&eacute;poser. Nous assurons la s&eacute;curit&eacute; des v&eacute;los d&eacute;pos&eacute;s pendant les deux journ&eacute;es de la bourse aux v&eacute;los y compris la nuit.', 2019, 'FAQ', 1, '2010-11-04 10:30:51', 'guy.rivallin@orange.fr'),
(47, 'Y a-t-il une garantie sur les v&eacute;los ?', 'Il y a une garantie seulement si le v&eacute;lo que vous ach&eacute;terez est encore sous garantie (cela arrive assez souvent). C&#39;est le cas de v&eacute;los achet&eacute;s r&eacute;cemment ne correspondant pas au besoin du propri&egrave;taire qui d&eacute;cide tr&egrave;s vite de profiter de la bourse et ses 5000 &agrave; 6000 visiteurs pour le revendre.', 2019, 'FAQ', 1, '2012-05-05 02:55:15', 'phil.frary@nthdimension.fr'),
(48, 'Est-il possible d&#39;&eacute;changer si on se trompe ?', 'Nous n&#39;avons jamais eu le cas mais si l&#39; acheteur constate tr&eacute;s vite (pendant le week-end) un probl&egrave;me de fonctionnement nous reprenons le v&eacute;lo et nous le sortons de la vente.', 2019, 'FAQ', 1, '2012-05-05 02:55:33', 'phil.frary@nthdimension.fr'),
(49, 'Quels sont les moyens de paiement ?', 'Par ch&egrave;que (carte d&#39;identit&eacute; demand&eacute;e) ou en num&eacute;raires. Nous ne pouvons utiliser de TPE car les ch&egrave;ques de l&#39;acheteur sont &eacute;mis &agrave; l&#39;ordre du vendeur.', 2019, 'FAQ', 1, '2012-05-05 02:55:51', 'phil.frary@nthdimension.fr'),
(50, 'Peut-on payer en plusieurs fois ?', 'Si nous avons cette demande , nous contactons par t&eacute;l&eacute;phone le vendeur qui lui seul d&eacute;cide mais nous avons toujours eu des r&eacute;ponses favorables &agrave; cette requ&ecirc;te pour des v&eacute;los de plus de 1000 &euro;', 2019, 'FAQ', 1, '2012-05-05 02:56:14', 'phil.frary@nthdimension.fr'),
(51, 'Est-il possible d&#39;essayer les v&eacute;los sur place ?', 'Les essais se font uniquement dans La Soucoupe pour des raison de s&eacute;curit&eacute; (vol). Une partie de cette tr&egrave;s grande salle est r&eacute;serv&eacute;e aux essais.<br />\nLes vendeurs de l&#39;association AVS sont l&agrave; pour vous conseiller.', 2019, 'FAQ', 1, '2012-05-05 02:56:28', 'phil.frary@nthdimension.fr'),
(52, 'Y a-t-il des v&eacute;los pour les enfants ?', 'Chaque ann&eacute;e, c&#39;est le coin qui bouge le plus car les enfants adorent essayer leurs nouveaux v&eacute;los. Nous en avons &agrave; tous les prix suivant leur &eacute;tat mais tous roulent tr&egrave;s bien.', 2019, 'FAQ', 1, '2012-05-05 02:56:42', 'phil.frary@nthdimension.fr'),
(53, 'Est-ce que c&rsquo;est &agrave; l&rsquo;abri ?', 'La Bourse aux v&eacute;los de l&#39;AVS est organis&eacute;e tous les ans et ce depuis novembre 2004 date de la 1ere &eacute;dition dans le gymnase (40x20) de St Marc sur Mer. Les v&eacute;los sont pr&eacute;sent&eacute;s sur des barri&egrave;res prot&eacute;g&eacute;es par de la mousse. Depuis l&#39;ann&eacute;e 2014, c&#39;est &agrave; La SOUCOUPE avenue L&eacute;o Lagrange St Nazaire. C&#39;est beaucoup plus grand (voir les photos sur ce site).', 2019, 'FAQ', 1, '2012-05-05 02:57:01', 'phil.frary@nthdimension.fr'),
(54, 'Je viens d&#39;apprendre l&#39;existence de votre bourse &agrave; v&eacute;los et je suis &agrave; la recherche d&#39;une paire de roues de v&eacute;lo de course.<br />\nEst-ce qu&#39;il y en aura &agrave; vendre d&#39;occasions ou bien votre club en revend-il ?', 'Chaque ann&eacute;e des paires de roues sont d&eacute;pos&eacute;es et elles trouvent acheteurs.<br />\nRDV &agrave; la 16eme &eacute;dition La Soucoupe de SAINT NAZAIRE LES 9 et 10 novembre 2019', 2019, 'FAQ', 1, '2013-04-13 08:19:53', 'chris.pierre2@sfr.fr'),
(55, 'Qui fixe le prix de vente des v&eacute;los pr&eacute;sent&eacute;s?', 'Apr&egrave;s avoir rempli la &quot;fiche d&eacute;p&ocirc;t&quot;, si le vendeur le souhaite, les &quot;estimeurs&quot; de l&#39;organisation sont &agrave; sa disposition pour fixer le &quot;bon&quot; prix.<br />\n&eacute;anmoins, c&#39;est le vendeur qui inscrit son prix de vente et il est le seul d&eacute;cideur.', 2019, 'FAQ', 1, '2013-10-29 18:22:07', 'phil.frary@nthdimension.fr'),
(56, 'J&#39;aimerais vendre mon v&eacute;lo &agrave; assistance &eacute;lectrique. Les VAE sont-ils les bienvenus lors de votre bourse aux v&eacute;los de St-Nazaire et en vendez-vous ?', 'L&#39;ann&eacute;e pass&eacute;e (2018), nous avions eu 4 v&eacute;los &eacute;lectriques &agrave; vendre, et 3 sont partis et donc ont trouv&eacute; preneur.<br />\nSoyez donc la bienvenue, beaucoup de personnes que je rencontre sont tr&egrave;s attir&eacute;e par ce genre de v&eacute;lo.<br />\nAttention &agrave; ne pas &ecirc;tre trop gourmande sur le prix!', 2019, 'FAQ', 1, '2013-10-29 18:41:24', 'phil.frary@nthdimension.fr'),
(57, 'bonjour, y a t&#39;il des remorques pour v&eacute;lo &agrave; vendre &agrave; la bourse aux v&eacute;los?', 'Bonjour<br />\nSi vous voulez parler de remorque qui s&rsquo;accrochent &agrave; des v&eacute;los: oui Benjamin, nous en avions plusieurs (une petite dizaine) en 2013. Elles sont toutes parties sauf une qui n&#39;&eacute;tait pas tr&egrave;s r&eacute;cente.<br />\nSi ce sont des remorques pour installer des v&eacute;los: non!<br />\nPar contre, nous avons eu &agrave; la vente des portes-v&eacute;los (4 v&eacute;los)<br />\nRdv &agrave; la Soucoupe les 14 et 15 octobre 2017.<br />\nMerci de votre confiance', 2019, 'FAQ', 1, '2014-08-24 09:16:09', 'benjamin_leray@hotmail.fr'),
(58, 'Comment puis je savoir si mon v&eacute;lo d&eacute;pos&eacute; est vendu?', 'Plusieurs solutions<br />\n1- Sur place &eacute;videmment en pr&eacute;sentant votre &quot;re&ccedil;u vendeur&quot;<br />\n2- Nouveau depuis 2014: en allant sur le site Internet de la Bourse aux v&eacute;los<br />\nCliquez sur l&#39;onglet: &quot;VENTE&quot;.<br />\nRentrez votre num&eacute;ro de v&eacute;lo dans la case. La r&eacute;ponse sera instantan&eacute;e.<br />\nSolution a privil&eacute;gier!!!<br />\n3- Par t&eacute;l&eacute;phone, au num&eacute;ro indiqu&eacute; sur votre &quot;re&ccedil;u vendeur&quot;', 2019, 'FAQ', 1, '2014-08-25 15:04:52', 'christian.pierre2@sfr.fr'),
(59, 'bonjour, pouvons nous vendre des roues carbones? merci', 'Bonjour,<br />\nSi vous parcourez le r&egrave;glement de La Bourse aux v&eacute;los de St Nazaire, on exclu les accessoires. N&eacute;anmoins chaque ann&eacute;e, des personnes nous confient pour la vente des accessoires genre porte-v&eacute;los, remorques, cadres et roues.<br />\nIl y a un march&eacute; pour du gros accessoire. (Condition de vente identiques aux v&eacute;los)<br />\nA bient&ocirc;t.', 2019, 'FAQ', 1, '2014-09-30 13:10:29', 'brissier.guillaume@orange.fr'),
(60, 'bjr ! melangez vous les vtt a petit prix avec ceux qui vale au moins 1300 e , comme le mien', 'Bonjour<br />\nLes VTT comme les autres v&eacute;los sont rang&eacute;s par genre et aussi par prix. Pour les beaux VTT, nous en avons toujours &agrave; chaque &eacute;dition et des beaucoup plus chers.<br />\nA bient&ocirc;t', 2019, 'FAQ', 1, '2015-11-03 11:36:50', 'matgin.falu@sfr.fr'),
(61, 'Suis je oblig&eacute; de revenir avant le dimanche soir 19h00 pour percevoir le montant de la vente si mon v&eacute;lo est affich&eacute; &quot;vendu&quot; sur le site?<br />\nJ&#39;habite Nantes. Merci!', 'Rappel de la proc&eacute;dure &laquo; de 30 km&raquo;<br />\nLe VENDEUR demande au moment du d&eacute;p&ocirc;t du v&eacute;lo l&rsquo;adresse o&ugrave; il pourra r&eacute;cup&eacute;rer le v&eacute;lo.<br />\nApr&egrave;s avoir v&eacute;rifi&eacute; par t&eacute;l&eacute;phone ou sur le site de la BAV que son v&eacute;lo a bien &eacute;t&eacute; vendu :<br />\nLe VENDEUR enverra par la Poste dans la semaine qui suit la BAV:<br />\n- le re&ccedil;u vendeur de couleur.<br />\n- une enveloppe timbr&eacute;e r&eacute;dig&eacute;e &agrave; son nom et son adresse.<br />\n- les 10 % par ch&egrave;que &agrave; l&rsquo;ordre de l&rsquo;AVS.<br />\nD&egrave;s r&eacute;ception, l&rsquo;AVS lui enverra le ch&egrave;que remis par l&rsquo;acheteur &agrave; l&rsquo;ordre du vendeur ou un ch&egrave;que de l&rsquo;AVS si le paiement s&rsquo;est fait en liquide', 2019, 'FAQ', 1, '2016-09-11 10:19:20', 'valerie.chausson@sfr.fr'),
(62, 'Avons nous la garantie des paiements, Ne risque t-il pas de recevoir un ch&egrave;que sans provisions', 'Bonjour Christophe<br />\nC&#39;est en effet la crainte des organisateurs que nous sommes. Nous demandons une pi&egrave;ce d&#39;identit&eacute; (2 pour les v&eacute;los de plus de 1000 &euro;) &agrave; l&#39;acheteur.<br />\nDepuis 14 ans le cas ne s&#39;est jamais produit.<br />\nMalheureusement, nous ne pouvons pas utiliser de terminaux de paiements car les achats se font &agrave; l&#39;ordre du vendeur.', 2019, 'FAQ', 1, '2016-09-20 10:54:34', 'cmoreil@free.fr'),
(63, 'Bonjour,<br />\nJe souhaiterais acqu&eacute;rir un nouveau v&eacute;lo de route car sur mon vieux v&eacute;lo de route j&#39;ai des douleurs aux &eacute;paules et en bas du dos. Pour ne pas me tromper sur l&#39;achat &agrave; la bourse aux v&eacute;los, il y a-t-il des personnes pouvant conseiller la bonne posture voire faire une &eacute;tude posturale ?<br />\nMerci', 'Bonjour Bertrand<br />\nNous avons la chance d&#39;avoir des professionnels de la vente de v&eacute;lo qui sont licenci&eacute;s dans le club organisateur. Ils sont pr&eacute;sents pour conseiller nos acheteurs. Je dirais que c&#39;est un peu un des points forts de la Bourse de l&#39;AVS.<br />\nA bientot', 2019, 'FAQ', 1, '2016-10-24 09:08:37', 'bertrand.maisonneuve@orange.fr'),
(64, 'Bonjour, pour cause de d&eacute;m&eacute;nagement je souhaite me s&eacute;parer d&#39;une centaine de livres concernant le cyclisme. Est-il possible de les vendre &agrave; cette occasion?<br />\nmerci pour votre r&eacute;ponse, cordialement.', 'Bonjour Philippe<br />\nNous ne vendons pas ni les accessoires ni les livres. Nous avons d&eacute;ja la vente de plus de 1000 v&eacute;los &agrave; g&eacute;rer et il faudtrait plus encore de b&eacute;n&eacute;voles pour que l&#39;on se diversifie. Nous sommes d&eacute;ja 90 &agrave; nous relayer pendant les 3 jours.<br />\nN&eacute;anmoins appeler moi car je connais et pourrais trouver des collectionneurs qui pourraient &ecirc;tre int&eacute;ress&eacute;s. (num&eacute;ro sur le site ou l&#39;affiche)<br />\nChristian', 2019, 'FAQ', 1, '2017-09-21 09:00:51', 'philippe.branchereau@bbox.fr'),
(65, 'Bonjour,<br />\nPourriez-vous m&#39;indiquer les heures d&#39;ouverture du samedi et dimanche.<br />\nD&#39;avance merci.', '<p>Bonjour<br />\n8h00 - 19h00 les 2 jours D&eacute;p&ocirc;ts et ventes<br />\nA bientot</p>\n', 2019, 'FAQ', 1, '2017-10-04 02:34:42', 'cocosn@orange.fr'),
(66, 'Bonsoir<br />\nJe souhaite mettre un beau v&eacute;lo en vente.<br />\nY a t&#39;il des mesures de protection des v&eacute;los.', 'Merci de poser cette question.<br />\n<strong><span style=\"background-color:#f39c12\">NOUVEAUTE: En 2019</span></strong>, nous ouvrons un show room pour les beaux v&eacute;los de plus de 500 &euro;.<br />\nCela se situera dans la mezzanine au dessus du hall d&#39;entr&eacute;e.<br />\nDans cet espace les v&eacute;los seront pr&eacute;sent&eacute;s debout bien espac&eacute;s. Ils seront bien mis en &eacute;vidence sur leurs supports pour faciliter les ventes.<br />\nComme indiqu&eacute; sur notre r&egrave;glement, nous mettons tout en oeuvre pour ne pas qu&#39;il y ait de probl&egrave;me.<br />\nVoir &eacute;galement la fiche pour les tr&egrave;s beaux velos.', 2019, 'FAQ', 1, '2018-11-10 16:42:00', 'Bourgemilie@sfr.fr'),
(67, 'Rencontrez le club v&eacute;lo Nazarien OCN', 'Pr&eacute;sence des membres du club v&eacute;lo OCN pendant la bourse aux v&eacute;los - venez les rencontrer sur place.<br />\n<img alt=\"\" height=\"463\" src=\"http://avs44.com/bourseauxvelos/ckeditorUploads/logo_ocn_2018.png\" width=\"591\" /> <a href=\"Images/animations/flyer_ocn_2018.pdf\" target=\"_blank\">Visualiser la presentation</a>', 2018, 'ANIM', 1, '2019-03-04 12:46:32', NULL),
(68, 'VOL DE VELOS', '<p>Pr&egrave;s de 500 000 v&eacute;los ont &eacute;t&eacute; d&eacute;clar&eacute;s vol&eacute;s en France en 2016, soit 1 369 v&eacute;los par jour.</p>\n\n<p>Venez rencontrer des b&eacute;n&eacute;voles de l&#39;association&nbsp;Place au Velo&nbsp;pour mieux vous prot&eacute;ger contre le vol de v&eacute;los<img alt=\"\" height=\"395\" src=\"http://avs44.com/bourseauxvelos/ckeditorUploads/logo_place_au_velo.png\" width=\"577\" /><br />\n<br />\n<a href=\"./Images/animations/flyer_vol_de_velo.pdf\" target=\"_blank\">&nbsp;Visualiser la presentation</a></p>\n', 2018, 'ANIM', 1, '2019-03-04 12:08:30', NULL),
(69, 'Gagnant Tombola', 'Heureuse gagnante en 2017 : Sylvie MORICE de La Baule qui part avec un VTT neuf marque TREK de chez &quot;Terre de Cycle&quot;, La Baule<br />\n<br />\n<img alt=\"\" src=\"http://avs44.com/bourseauxvelos/ckeditorUploads/gagnant_tombola_2017.jpg\" />', 2017, 'ANIM', 1, '2017-05-04 11:52:53', NULL),
(70, 'Herv&eacute; LEDUC<br />\nDimanche 15 octobre 15h00', 'Conf&eacute;rence diaporama par Herv&eacute; Leduc.&nbsp;<br />\nApr&egrave;s Sandrine Laporal, pr&eacute;sente &agrave; la BAV 2016, qui &eacute;tait venue suite &agrave; sa travers&eacute;e du Canada &agrave; v&eacute;lo, place &agrave; une autre conf&eacute;rence d&eacute;bat.<br />\n<br />\n<img alt=\"\" src=\"http://avs44.com/bourseauxvelos/ckeditorUploads/leduc_1.jpg\" />', 2017, 'ANIM', 1, '2017-03-04 12:53:45', NULL),
(71, '&quot;Un homme, un v&eacute;lo, une aventure!&quot;', 'En trois mots, c&#39;est ainsi que le nazairien Herv&eacute; Leduc a coutume de r&eacute;sumer le p&eacute;riple autour du monde qu&#39;il a accompli en v&eacute;lo.<br />\nIl vous parlera lors de cette conf&eacute;rence, de son p&eacute;riple retra&ccedil;ant les 54 650 km parcourus &agrave; travers 34 pays . Il a notamment les d&eacute;serts du Thar en Inde ou le Taklamakan en Chine.<br />\nA la fin, il pourra vous d&eacute;dicacer son livre de 250 pages.<br />\n&quot;A tous ceux que cela titille,je leur dis de prendre la route&quot; se plait &agrave; dire Herv&eacute;.<br />\n<br />\n<br />\n<img alt=\"\" src=\"http://avs44.com/bourseauxvelos/ckeditorUploads/leduc_2.jpg\" />', 2017, 'ANIM', 1, '2017-03-04 12:54:39', NULL),
(72, 'Gagnant Tombola', 'Heureuse gagnante en 2016 : Sandrine BONNET de ST NAZAIRE qui part avec un VTT neuf marque TREK de chez &quot;Terre de Cycle&quot;, La Baule<br />\n<br />\n<img alt=\"\" src=\"http://avs44.com/bourseauxvelos/ckeditorUploads/gagnant_tombola_2016.jpg\" />', 2016, 'ANIM', 1, '2016-03-04 12:59:11', NULL),
(73, 'Tombola', 'Pendant l&#39;&eacute;dition 2016, chaque acheteur, vendeur ou visiteur pourra s&#39;il le souhaite participer &agrave; la tombola gratuite de la Bourse aux V&eacute;los pour gagner un tr&egrave;s beau VTT 26 pouces NEUF de chez &quot;Terre de Cycle&quot; &agrave; La Baule.<br />\nTirage au sort le dimanche soir vers 17h30.<br />\n<br />\n<a href=\"Images/animations/tombola_flyer_2016.pdf\" target=\"_blank\"><img alt=\"\" src=\"http://avs44.com/bourseauxvelos/ckeditorUploads/tombola_prize_2016.png\" /></a>', 2016, 'ANIM', 1, '2016-03-04 13:03:36', NULL),
(74, 'Rencontres', '<div><img alt=\"\" height=\"121\" src=\"http://avs44.com/bourseauxvelos/ckeditorUploads/meeting_place.jpg\" style=\"float:right\" width=\"121\" /></div>\n<br />\nPr&eacute;sence des clubs v&eacute;los nazairiens durant toute la bourse<br />\nVenez rencontrer des repr&eacute;sentants des clubs qui sauront vous renseigner sur leur activit&eacute;s.<br />\nClubs pr&eacute;sents: OCN; CRI; AVS; SNBC.<br />\n<br />\nUne invit&eacute;e sp&eacute;ciale vous pr&eacute;sentera son aventure &agrave; grande &eacute;chelle<br />\n&nbsp;\n<div style=\"text-align:justify\"><img alt=\"\" height=\"87\" src=\"http://avs44.com/bourseauxvelos/ckeditorUploads/cri.jpg\" width=\"87\" /><img alt=\"\" height=\"88\" src=\"http://avs44.com/bourseauxvelos/ckeditorUploads/avs.jpg\" width=\"88\" /><img alt=\"\" height=\"75\" src=\"http://avs44.com/bourseauxvelos/ckeditorUploads/snbc.jpg\" width=\"75\" /></div>\n', 2016, 'ANIM', 1, '2016-03-04 12:05:59', NULL),
(75, 'Sandrine LAPORAL', '<img alt=\"\" height=\"129\" src=\"http://avs44.com/bourseauxvelos/ckeditorUploads/canada_2016.png\" style=\"float:right\" width=\"150\" /><br />\nLicenci&eacute;e &agrave; la FFCT, Sandrine LAPORAL a v&eacute;cu une exp&eacute;rience qui fera r&ecirc;ver plus d&rsquo;un(e) cyclotouriste. Venez nombreux<br />\nSandrine pr&eacute;sentera une conf&eacute;rence le dimanche &agrave; La Bourse aux V&eacute;los (horaires &agrave; d&eacute;finir).<br />\n<br />\n<img alt=\"\" src=\"http://avs44.com/bourseauxvelos/ckeditorUploads/sandrinelaporal_2016.png\" />', 2016, 'ANIM', 1, '2016-02-04 13:11:49', NULL),
(76, 'La concertation v&eacute;lo &agrave; St Nazaire', '<img alt=\"\" height=\"122\" src=\"http://avs44.com/bourseauxvelos/ckeditorUploads/stnazaire_logo.jpg\" style=\"float:right\" width=\"236\" />Vous trouverez en plus cette ann&eacute;e un stand ville de St Nazaire pour vous informer dans le cadre de la concertation sur le plan &quot;v&eacute;lo&quot; dans la ville. Vous pourrez lors de votre passage dialoguer avec les responsables sur les d&eacute;placements doux.<br />\n<br />\nVoir sur le &nbsp;site de la <a href=\"http://www.mairie-saintnazaire.fr/404/404-saintnazaire.php\" target=\"_blank\">ville</a> la concertation.', 2016, 'ANIM', 1, '2016-01-05 12:51:30', NULL),
(77, 'Gagnant Tombola', '<img alt=\"\" src=\"http://avs44.com/bourseauxvelos/ckeditorUploads/gagnant_tombola_2015.jpg\" style=\"float:right\" />\nHeureux gagnant en 2015 : M. Thomas NAEL de ST NAZAIRE qui part avec un VTT neuf marque TREK de chez Bike Earth, St Nazaire', 2015, 'ANIM', 1, '2015-03-06 12:55:19', NULL),
(78, 'Tombola', '<img alt=\"\" src=\"http://avs44.com/bourseauxvelos/ckeditorUploads/tombola_prize_2015.jpg\" style=\"float:right\" />Pendant l&#39;&eacute;dition 2015, chaque acheteur, vendeur ou visiteur pourra s&#39;il le souhaite participer &agrave; la tombola gratuite de la Bourse aux V&eacute;los pour gagner un tr&egrave;s beau VTT 26 pouces NEUF MARQUE TREK de chez &quot;Bike Earth&quot; St Nazaire. Tirage au sort le dimanche soir vers 17h30.', 2015, 'ANIM', 1, '2015-03-05 12:56:25', NULL),
(79, 'Ch&egrave;que au m&eacute;c&eacute;nat chirurgie cardiaque', '<img alt=\"\" src=\"http://avs44.com/bourseauxvelos/ckeditorUploads/mecenat_lg.jpg\" />', 2014, 'ANIM', 1, '2014-03-05 12:58:49', NULL),
(80, 'Gagnant Tombola', 'Le VTT (valeur 529 &euro;) qui a &eacute;t&eacute; gagn&eacute; lors de la Bourse aux V&eacute;los 2014 a &eacute;t&eacute; remis &agrave; la gagnante devant le magasin Bike Earth en pr&eacute;sence des membres du bureau de l&#39;ATLANTIQUE VELO SPORT.<img alt=\"\" src=\"http://avs44.com/bourseauxvelos/ckeditorUploads/gagnant_tombola_2014-lg.jpg\" />', 2014, 'ANIM', 1, '2014-03-05 13:01:34', NULL),
(81, 'Paul Correc', '<img alt=\"\" height=\"566\" src=\"http://avs44.com/bourseauxvelos/ckeditorUploads/paul_correcof_2_sm.jpg\" width=\"400\" /><br />\nPaul CORREC sera pr&eacute;sent samedi et dimanche apr&egrave;s-midi dans l&#39;enceinte de la soucoupe &agrave; l&#39;occasion de la Bourse aux V&eacute;los pour pr&eacute;senter son ouvrage consacr&eacute; &agrave; un si&egrave;cle de cyclisme &agrave; St Nazaire.<br />\nA cette occasion, vous pourrez achetez ce livre et le faire d&eacute;dicacer par l&#39;auteur. Cette ouvrage est publi&eacute; par l&#39;Association Pr&eacute;historique et Historique de la R&eacute;gion Nazairienne.', 2014, 'ANIM', 1, '2014-02-05 13:02:51', NULL),
(82, 'Gagnant Tombola', 'Heureux gagnant en 2013 : M. THOMAS de GUERANDE qui part avec un nouveau VTT 26&quot; de chez Bike Earth, St Nazaire<br />\n<img alt=\"\" height=\"266\" src=\"http://avs44.com/bourseauxvelos/ckeditorUploads/gagnant_tombola_2013_2.jpg\" width=\"400\" />', 2013, 'ANIM', 1, '2013-02-04 13:04:23', NULL),
(83, 'Bruno LEZIN', 'Bruno LEZIN que l&#39;on ne pr&eacute;sente plus sur St Nazaire. Il a suivi de nombreux Tour de France. Il a &eacute;crit un livre sur le tour et il pr&eacute;sente de nombreux objets revues et visuels de la grande boucle ainsi que des maillots prestigieux ayant appartenus &agrave; des stars du v&eacute;lo.<br />\n<img alt=\"\" height=\"300\" src=\"http://avs44.com/bourseauxvelos/ckeditorUploads/lezin.jpg\" width=\"400\" />', 2013, 'ANIM', 1, '2013-01-05 13:05:41', NULL),
(84, 'Daniel COUDE', 'Originaire de Tour, grand habitu&eacute; de la bourse aux v&eacute;los de St NAZAIRE, il est un grand collectionneur de v&eacute;los. Il nous en pr&eacute;sentera quelques uns et vous fera partager sa passion.<br />\n<img alt=\"\" height=\"300\" src=\"http://avs44.com/bourseauxvelos/ckeditorUploads/coude.jpg\" width=\"400\" />', 2013, 'ANIM', 1, '2013-01-05 13:06:09', NULL),
(85, 'Jean THEIL', 'Passionn&eacute; de v&eacute;lo et de son histoire, habitant Pr&eacute;failles, il nous pr&eacute;sentera sur une quinzaine de grilles des tableaux qu&#39;il a confectionn&eacute;s lui m&ecirc;me et qui retracent l&#39;histoire de la petite reine.<br />\n<img alt=\"\" height=\"266\" src=\"http://avs44.com/bourseauxvelos/ckeditorUploads/theil.jpg\" width=\"400\" />', 2013, 'ANIM', 1, '2013-01-05 13:06:34', NULL),
(86, 'Heureuse gagnante en 2012', 'Sylvie MARIN de SAINT NAZAIRE qui part avec un nouveau VTC 29&quot; de chez Intersport Trignac<br />\n<img alt=\"\" src=\"http://avs44.com/bourseauxvelos/ckeditorUploads/gagnant_tombola_2012-lg.jpg\" />', 2012, 'ANIM', 1, '2012-03-05 13:08:43', NULL),
(87, 'Gagnant Tombola', 'En 2011, J&eacute;rome ROBERT de St Nazaire a gagn&eacute; un VTC neuf<br />\n<br />\n<img alt=\"\" src=\"http://avs44.com/bourseauxvelos/ckeditorUploads/gagnant_tombola_2011.jpg\" />', 2011, 'ANIM', 1, '2011-03-05 13:09:13', NULL),
(90, 'Tombola', '<img alt=\"\" height=\"115\" src=\"http://avs44.com/bourseauxvelos/ckeditorUploads/terre_de_cycle_logo.png\" width=\"396\" /><br />\r\nPendant l&#39;&eacute;dition 2019, chaque acheteur, vendeur ou visiteur pourra s&#39;il le souhaite participer &agrave; la tombola gratuite de <strong>la Bourse aux V&eacute;los </strong>pour gagner un tr&egrave;s beau VTT NEUF de chez &quot;<strong>Terre de Cycle</strong>&quot; &agrave; La Baule.<br />\r\nTirage au sort le dimanche soir vers 17h30.<br />\r\n<br />\r\n==&gt;&nbsp;<a href=\"http://avs44.com/bourseauxvelos/downloads/reglement_tombola.pdf\" target=\"_blank\">reglement de la tombola</a>', 2019, 'ANIM', 1, '2019-02-07 12:02:48', NULL),
(91, 'Rencontrez le club v&eacute;lo Nazarien OCN', 'Pr&eacute;sence des membres du club v&eacute;lo OCN pendant la bourse aux v&eacute;los - venez les rencontrer sur place.<br />\r\n<img alt=\"\" height=\"463\" src=\"http://avs44.com/bourseauxvelos/ckeditorUploads/logo_ocn_2018.png\" width=\"591\" /> <a href=\"Images/animations/flyer_ocn_2018.pdf\" target=\"_blank\">Visualiser la presentation</a>', 2019, 'ANIM', 1, '2019-03-04 12:46:32', NULL),
(92, 'Bruno LEZIN', 'Bruno LEZIN que l&#39;on ne pr&eacute;sente plus sur St Nazaire. Il a suivi de nombreux Tour de France. Il a &eacute;crit un livre sur le tour et il pr&eacute;sente de nombreux objets revues et visuels de la grande boucle ainsi que des maillots prestigieux ayant appartenus &agrave; des stars du v&eacute;lo.<br />\r\n<img alt=\"\" height=\"300\" src=\"http://avs44.com/bourseauxvelos/ckeditorUploads/lezin.jpg\" width=\"400\" />', 2019, 'ANIM', 0, '2013-01-05 13:05:41', NULL),
(93, 'VOL DE VELOS', '<p>Pr&egrave;s de 500 000 v&eacute;los ont &eacute;t&eacute; d&eacute;clar&eacute;s vol&eacute;s en France en 2016, soit 1 369 v&eacute;los par jour.</p>\r\n\r\n<p>Venez rencontrer des b&eacute;n&eacute;voles de l&#39;association&nbsp;Place au Velo&nbsp;pour mieux vous prot&eacute;ger contre le vol de v&eacute;los<img alt=\"\" height=\"395\" src=\"http://avs44.com/bourseauxvelos/ckeditorUploads/logo_place_au_velo.png\" width=\"577\" /><br />\r\n<br />\r\n<a href=\"./Images/animations/flyer_vol_de_velo.pdf\" target=\"_blank\">&nbsp;Visualiser la presentation</a></p>\r\n', 2019, 'ANIM', 1, '2019-09-16 11:08:30', NULL),
(95, 'Bonjour, j&#39;ai plusieurs v&eacute;los &agrave; vendre. Existe t il un nombre maximal de d&eacute;pots par vendeur ?', 'Bonjour&nbsp;<br />\nNon il n&#39;existe pas de limite au nombre de v&eacute;los, mais si vous d&eacute;posez plus de 15 v&eacute;los, contactez nous <a href=\"mailto:bourse1000velos@avs44.com?subject=Demande%20info%20proc%C3%A9dure%20%22gros%20vendeur%22\">bourse1000velos@avs44.com</a> , nous avons une proc&eacute;dure sp&eacute;ciale pour cela.<br />\n<br />\nCdt<br />\n&nbsp;', 2019, 'FAQ', 1, '2019-10-16 16:16:26', NULL),
(96, 'Tombola 2019', '<p>Tombola ouverte &agrave; tous: VTT superbe de chez &quot;<a href=\"https://www.terredecycle.com/\" target=\"_blank\">Terre de Cycle</a>&quot; &agrave; La Baule. Dimitri qui vous pr&eacute;sente le vtt 29 pouces 2019 et qui fera parti des nombreux b&eacute;n&eacute;voles qui seront pr&eacute;sents &agrave; la Soucoupe pour vous aider &agrave; choisir votre v&eacute;lo</p>\n\n<img alt=\"\" height=\"400\" src=\"http://avs44.com/bourseauxvelos/ckeditorUploads/783eb41b.jpg\" />', 2019, 'ANIM', 1, '2019-10-17 07:05:17', NULL),
(97, 'Bonjour,&nbsp;<br />\nSvp, y a t&rsquo;il possibilit&eacute; de d&eacute;poser un porte v&eacute;lo Hayon &agrave; la bourse aux v&eacute;los ?&nbsp;<br />\n&nbsp;', NULL, 2019, 'FAQ', 0, '2019-11-03 18:56:40', NULL),
(99, 'R&eacute;sultat Tombola', 'F&eacute;lication au gagant, qui termine bien leur week end, apr&egrave;s avoir vendu 2 v&eacute;los et en achet&eacute; de 2 autres..&nbsp;&nbsp;<br />\n<img alt=\"Vainqueur Tombola 2019\" height=\"225\" src=\"http://avs44.com/bourseauxvelos/ckeditorUploads/79a02d82.jpg\" width=\"400\" />', 2019, 'ANIM', 1, '2019-11-13 18:28:56', NULL);

--
-- Index pour les tables exportées
--

--
-- Index pour la table `bav_actu`
--
ALTER TABLE `bav_actu`
  ADD UNIQUE KEY `act_id` (`act_id`);

--
-- AUTO_INCREMENT pour les tables exportées
--

--
-- AUTO_INCREMENT pour la table `bav_actu`
--
ALTER TABLE `bav_actu`
  MODIFY `act_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=100;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
